<?php
/**
 * @package     FOM
 * @subpackage  Textos Compras
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http//www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 **/
$textos = array(
    /*Basicos*/
    'MODULO_ACTUAL'                             => 'Compras',
    'ADICIONAR_ITEM'                            => 'Agregar Compra',
    'MODIFICAR_ITEM'                            => 'Modificar Compra',
    'ELIMINAR_ITEM'                             => 'Eliminar Compra',
    'CONSULTAR_ITEM'                            => 'Consultar Compra',
    'BUSCAR_ITEM'                               => 'Buscar Compra',
    'CONFIRMAR_ACCION_FACTURA'                  => 'Qué desea hacer con la factura de compra?',
    'ACCION_EJECUTADA'                          => 'Acción Ejecutada',
    'GENERAR_ORDEN_COMPRA'                      => 'Generar Orden de Compra ......... Ctrl + O',
    'IMPRIMIR_FACTURA_IMPRESORA'                => 'Imprimir Factura en Impresora ..... Ctrl + I',
    'IMPRIMIR_FACTURA_POS'                      => 'Imprimir factura POS .................... Ctrl + P',
    'CANCELAR'                                  => 'Cancelar ......................................... Ctrl + Q',
    'FACTURA_COMPRA_NUM'                        => 'Factura de compra número  %1 ',
    'GENERAR_FACTURA_DESDE_FACTURA_TEMPORAL'    => 'Recuperar factura fecha %1',
    'MODIFICAR_FACTURA'                         => 'Modificar Factura',
    'GENERAR_FACTURA_DESDE_ORDEN'               => 'Generar Factura desde Orden de Compra N° %1',
    'CREAR_ORDEN_COMPRA'                        => 'Crear Orden de Compra',
    'SELECCIONAR'                               => 'Seleccionar',
    'SELECCIONE_FECHA_FINAL'                    => 'Seleccione fecha final',
    'SELECCIONE_FECHA_INICIAL'                  => 'Seleccione fecha inicial',
    'NUMERO_DE_FACTURA'                         => 'Numero de factura',
    'AYUDA_SELECCIONAR_ITEMS_TABLA_FACTURAS'    => '*Haga click derecho sobre una fila para ver la factura en detalle',
    'CARGAR_ORDEN_COMPRA'                       => '<span ayuda="Cargar Orden de Compra">Cargar O.C</span>',
    'MENSAJE_FACTURA_TEMPORAL_COMPRA'           => 'Tienes una copia de factura de <span class=negrilla>compra</span> sin finalizar realizada el <span class=negrilla>%1</span> al proveedor <span class=negrilla>%2</span>', 
    'BUSCAR_ORDENES'                            => 'Buscar Ordenes',
    'ES_ORDEN_COMPRA'                           => 'Es una orden de compra',
    'FECHA_ORDEN'                               => 'Fecha orden',
    'NUMERO_DE_ORDEN'                           => 'N° de orden',
    'NIT_PROVEEDOR'                             => 'Nit proveedor',
    
    'NIT'                                       => 'Nit',
    'SOLO_PUEDE_SER_ORDEN_COMPRA'               => '* Falta el campo \'Número de factura de proveeedor\', solo puedes ejecutar una orden de compra.',
    'CREAR_FACTURA_PROVEEDOR'                   => 'Generar copia de factura de proveedor',
    'EDITAR_FACTURA_PROVEEDOR'                  => 'Editar factura de proveedor',
    'HORA'                                      => 'Hora',
    'CATALOGOS'                                 => 'Catálogos',
    'BUSCAR_CATALOGOS'                          => 'Click aquí para buscar el<br> catálogo de una moto',
    'TIPO_DE_FACTURA'                           => 'COPIA FACTURA DE COMPRA',
    'FECHA_FACTURA'                             => 'Fecha de Factura',
    'USUARIO_QUE_FACTURA'                       => 'Usuario que Factura',
    'FECHA_VENCIMIENTO'                         => 'Fecha de Vencimiento',
    'DESCUENTOS'                                => 'Descuentos',
    'TOTAL_DESCUENTOS'                          => 'Total descuentos',
    'PAGINA'                                    => 'Página',
    'EMAIL'                                     => 'E-mail',
    'NOTA'                                      => 'Nota',
    'MOVER'                                     => 'Mover',
    'ID_AUTOMATICO'                             => 'Id Auto.',
    'CODIGO_OEM'                                => 'Cod. OEM',
    'REFERENCIA'                                => 'Ref.',
    'MOVER_ARTICULO_BODEGA'                     => 'Mover articulo a bodega diferente',
    'BUSCAR_ORDEN_COMPRA'                       => 'Buscar Orden de Compra',
    'INGRESE_NUM_ORDEN_COMPRA'                  => 'Ingrese el N° de Orden de Compra',
    'BUSQUEDA_AVANZADA'                         => 'Busqueda avanzada >>',
    'AYUDA_BUSCAR_FACTURAS'                     => 'Click aquí para Buscar<br> Facturas en el sistema',//'Buscar factura',
    'BUSCAR_FACTURA'                            => 'Buscar factura',
    'PORCENTAJE_GANANCIA'                       => '% ganancia',
    'RETECREE'                                  => 'Retecree',
    'TOTAL_RETENCIONES'                         => 'Total retenciones',
    'TOTAL_A_PAGAR'                             => 'Total a pagar',
    'ACTUALIZAR_RETENCIONES'                    => 'Actualizar valores de retenciones',
    'DCTO_TOTAL_ARTICULOS'                      => 'Dcto. total Articulos',
    

    
    /*Campos y labels*/
    'NOMBRE'                                    => 'Nombre',
    'CODIGO'                                    => 'Codigo ',
    'NUMERO_FACTURA'                            => 'Factura de Compra N° ',
    'NUMERO_FACTURA_PROVEEDOR'                  => 'N° Fact. Proveedor ',
    'FECHA'                                     => 'Fecha ',
    'PROVEEDOR'                                 => 'Proveedor ',
    'OBSERVACIONES'                             => 'Observaciones ',
    'LISTA_ARTICULOS'                           => 'Listado de Articulos ',
    'CONCEPTO'                                  => 'Concepto ',
    'DESCUENTO1'                                => 'Descuento 1 ',
    'DESCUENTO2'                                => 'Descuento 2 ',
    'MAS_DESCUENTO'                             => '+ dcto',
    'ARTICULO'                                  => 'Articulo ',
    'VALOR_FLETE'                               => 'Valor flete ',
    'IVA'                                       => 'I.V.A ',
    'IVA_TOTAL'                                 => 'I.V.A total',
    'MODO_PAGO'                                 => 'Modo de Pago',
    'MODO_PAGO'                                 => 'Modo de Pago',
    'MODO_PAGO1'                                => 'Contado',
    'MODO_PAGO2'                                => 'Credito',    
    'CREDITO'                                   => 'Credito',
    'CONTADO'                                   => 'Contado',
    'VENCIMIENTO'                               => 'Vencimiento ',
    'TOTAL'                                     => 'Total ',
    'AGREGAR'                                   => 'Agregar',
    'DESCUENTO_GENERAL'                         => 'Dcto. General ',
    'DESCUENTO'                                 => 'Descuento',
    'SUBTOTAL'                                  => 'Subtotal',
    'REFERENCIA'                                => 'Referencia',
    'FINALIZAR_FACTURA'                         => 'Fin Factura',
    'PRECIO_UNITARIO'                           => 'Precio U.',
    'VER_MAS'                                   => 'Click para ver más sobre el item',
    'MOTO'                                      => 'Moto',
    'SUBGRUPO'                                  => 'Subgrupo',
    'GRUPO'                                     => 'Grupo',
    'PRESENTACION'                              => 'Presentacion (empaque)',
    'PLU'                                       => 'Plu',
    'LINEA'                                     => 'Linea',
    'MARCA'                                     => 'Marca',
    'MODELO'                                    => 'Modelo',
    'MEDIDAS'                                   => 'Medidas',
    'CANTIDAD'                                  => 'Cantidad',
    'PRECIO_COMPRA'                             => 'Precio de Compra',
    'PRECIO_COMPRA_ANTERIOR'                    => 'Precio de Compra Anterior',
    'MARGEN_GANANCIA'                           => 'Margen de Ganancia',
    'APLICACION_EXTRA'                          => 'Aplicacion extra',
    'NACIONALIDAD'                              => 'Nacionalidad',
    'MARGEN_GANANCIA_PESOS'                     => 'Margen de Ganancia en Pesos',
    'MARGEN_GANANCIA_PORCENTAJE'                => 'Margen de Ganancia en Procentaje',
    'PRECIO_BASE'                               => 'Precio Venta',
    'LARGO'                                     => 'Largo',
    'ANCHO'                                     => 'Ancho',
    'ALTO'                                      => 'Alto',
    'EL_CODIGO'                                 => 'Codigo %1',
    'EL_NOMBRE'                                 => 'Nombre %1',
    'CODIGO_COMERCIAL'                          => 'Codigo comercial',
    'CODIGO_ISO'                                => 'Codigo iso',
    'AYUDA_CODIGO_ISO'                          => 'Codigo iso internacional del pais<br> compuesto por dos letras mayusculas',
    'BANDERA'                                   => 'Bandera',
    'SELECCIONAR_MOTOS_APLICACION'              => 'Seleccione a que motos sirve este articulo',
    'APLICA_SOLO_SU_MOTO'                       => 'Sirve solo a una moto',
    'APLICA_VARIAS_MOTOS'                       => 'Sirve a varias motos',
    'LLEVA_IVA'                                 => 'Lleva iva',
    'NO_LLEVA_IVA'                              => 'No lleva iva',
    'MOTOS_APLICABLE'                           => 'Aplica a las siguientes motos',
    'TEXTO_IVA_1'                               => 'Aplica IVA',
    'TEXTO_IVA_2'                               => 'NO Aplica IVA',
    'APLICABILIDAD_MOTOS'                       => 'Otras motos en que aplica',
    'PRECIOS'                                   => 'Precios',
    'PRECIO'                                    => 'Precio',
    'UBICACION'                                 => 'Ubicación',
    'BODEGA'                                    => 'Bodega',
    'GONDOLA'                                   => 'Gondola',
    'SEDE'                                      => 'Sede',
    'CONCEPTO1'                                 => 'Concepto1',
    'PRECIOS'                                   => 'Precios',
    'PRECIO1'                                   => 'Precio1',
    'CONCEPTO2'                                 => 'Concepto2',
    'PRECIO2'                                   => 'Precio2',
    'CONCEPTO3'                                 => 'Concepto3',
    'PRECIO3'                                   => 'Precio3',
    'CONCEPTO4'                                 => 'Concepto 4',
    'PRECIO4'                                   => 'Precio4',  
    'PRECIO_VENTA'                              => 'Precio venta',
    'PRECIO_VENTA1'                             => 'Precio de venta 1',
    'PRECIO_VENTA2'                             => 'Precio de venta 2',
    'PRECIO_VENTA3'                             => 'Precio de venta 3',
    'PRECIO_VENTA4'                             => 'Precio de venta 4',
    'INFORMACION_ARTICULO'                      => 'Información Articulo',
    'INFORMACION_APLICABILIDAD'                 => 'Información de aplicación',
    'INFORMACION_PRECIOS'                       => 'Información precios',
    'BUSCAR_FACTURAS'                           => 'Buscar Facturas',
    'FECHA_INICIAL'                             => 'Fecha inicial',
    'FECHA_FINAL'                               => 'Fecha final',
    'AGREGAR_VARIOS_ARTICULOS'                  => 'Varios articulos',
    'FACTURA_GENERADA_EXITOSAMENTE'             => 'Factura generada exitosamente',
    'PROVEEDOR_ESTANDAR'                        => 'COMPRA VARIOS DE CONTADO',
    'CAJA'                                      => 'Caja',
    'GANANCIA_GENERAL'                          => 'Ganancia general',
    'IMPRIMIR_CODIGOS_BARRA'                    => 'Desea imprimir los códigos de barra de los articulos?',
    
    
    
    
    /*Errores*/
    'ERROR_FALTA_CODIGO'                        => 'Error falta codigo',
    'ERROR_EXISTE_CODIGO'                       => 'Error existe un pais con este codigo iso',
    'ERROR_EXISTE_CODIGO_COMERCIAL'             => 'Error existe un pais con este codigo comercial',
    'ERROR_FALTA_NOMBRE'                        => 'Error falta nombre', 
    'ERROR_EXISTE_NOMBRE'                       => 'Error existe un articulo registrado con ese nombre',
    'ERROR_FORMATO_CODIGO'                      => 'Error formato codigo iso, solo deben ser dos letras mayusculas',
    'ERROR_FORMATO_NOMBRE'                      => 'Error formto nombre, deben ser solo letras',
    'ERROR_FALTA_SUBGRUPO'                      => 'Error falta subgrupo',
    'ERROR_SUBGRUPO_INEXISTENTE'                => 'Error, debe seleccionar un subgrupo de la lista',
    'ERROR_FALTA_GRUPO'                         => 'Error falta grupo',
    'ERROR_GRUPO_INEXISTENTE'                   => 'Error, debe seleccionar un grupo de la lista',    
    'ERROR_MOTO_INEXISTENTE'                    => 'Error, debe seleccionar una moto de la lista',
    'ERROR_PAIS_INEXISTENTE'                    => 'Error, debe seleccionar un pais de la lista',
    'ERROR_UNIDAD_INEXISTENTE'                  => 'Error, debe seleccionar una unidad de la lista',
    'ERROR_MARCA_INEXISTENTE'                   => 'Error, debe seleccionar una marca de la lista',
    'ERROR_FALTA_REFERENCIA'                    => 'Error, falta referencia',
    'ERROR_FALTA_UNIDAD'                        => 'Error, falta unidad',
    'ERROR_FALTA_PAIS'                          => 'Error, falta pais',
    'ERROR_FACTURA_SIN_ARTICULOS'               => 'Error, debes ingresar al menos un articulo',
    'ERROR_FALTA_PRECIO_BASE'                   => 'Error, debes introducir almenos un precio de venta',
    'ERROR_FALTA_PRECIO_COMPRA'                 => 'Error, falta precio compra',
    'ERROR_FALTA_MARGEN_GANANCIA'               => 'Error, falta margen ganancia',
    'NUMERO_FACTURA_EXISTENTE_EN_PROVEEDOR'     => 'Este proveedor ya tiene este número de factura en una compra previa con N° de Factura de compra  %1',
    
    /*Ayuda*/
    'AYUDA_FECHA_FACTURA'                       => 'Aquí puedes cambiar la<br> fecha de la factura',
    'SELECCIONE_MEDIO_DE_PAGO'                  => 'Selecciona la forma de pago',
    'AYUDA_GANANCIA_GENERAL'                    => 'Ingresa en este campo el <br> porcentaje de ganacia para <br> todos los articulos',
    'AYUDA_DESCUENTO_GENERAL'                   => 'Ingresa en este campo el <br> descuento general para <br> todos los articulos',
    'AYUDA_FECHA_VTO_FACTURA'                   => 'Selecciona la fecha límite<br> para el pago de la factura',
    'AYUDA_CARGAR_ORDEN_COMPRA'                 => 'Click aquí para buscar una orden<br>de compra y cargarla.',
    'AYUDA_MODULO'                              => '<p>* F1 Para agregar varios articulos al tiempo </p><p>* F2 Para buscar facturas  </p><p>* Shift + M para cerrar el menu superior.</p><p><p class = \'videotutorialAyuda\'>* <a onclick=\'cerrarAyuda()\' rel=\'prettyPhoto[]\' href=\'http//www.youtube.com/watch?v=x6UODla2hqE\' target=\'blank\'>Click Aqui para ver video de ayuda paso a paso</a></p>*Para cerrar esta ventana presione Ctrl+H, o haga click en cualquier lugar <br>',

    /* Ayuda tutorial*/
    'AYUDA_SELECCIONAR_PROVEEDOR'               => 'Seleccione el proveedor al que se le va a realizar la compra',
    'AYUDA_INGRESAR_ARTICULO_A_LA_FACTURA'      => 'escribe algún caracter para iniciar la busqueda de un articulo, puedes buscar por descripción, PLU, o referencia. Al seleccionarlo ya sea haciendo click con el mouse, o moviendose con las flechas del teclado y presionando enter, automáticamente se agregará al listado de articulos',
    'AYUDA_INGRESA_NUM_FACTURA_PROVEEDOR'       => 'Ingrese aquí el número de factura del proveedor. Si no se ingresa valores en este campo, solo se podrá realizar una orden de compra.',
    'AYUDA_INGRESA_FECHA_COMPRA'                => 'Ingrese aquí la fecha en la que se ejecuta esta compra, por defecto es la fecha actual.',
    'AYUDA_BUSCAR_FACTURAS_ANTERIORES'          => 'Click aquí para desplegar el formulario donde podras buscar facturas de compra realizadas en el sistema. En dicho formulario podras escoger un proveedor en particular y un rango de fechas, al hacer click en aceptar el sistema mostrará un listado con las facturas realizadas al proveedor seleccionado en el rango de fechas seleccionado.',
    'AYUDA_BUSCAR_CATALOGO_MOTO'                => 'Click aquí para desplegar el formulario donde podras buscar el catálogo de una moto. El formulario mostrará un campo de texto autocompletable donde podras buscar y seleccionar una moto en particular y el sistema desplegará el catálogo de dicha moto.',
    'AYUDA_BUSCAR_Y_CARGAR_ORDEN_DE_COMPRA'     => 'Click aquí para desplegar el formulario donde podras buscar ordenes de compra realizadas en el sistema. Podras realizar una busqueda simple (por el número de orden), o más avanzada (escoger un proveedor y un rango de fechas), el sistema desplegará un listado con todas las ordenes de compra coincidientes. Haga click derecho sobre la orden de compra que desea consultar y allí encontrará la opción para generar una factura a partir de dicha orden.',
    'AYUDA_CARGAR_MULTIPLES_ARTICULOS'          => 'Click aquí para que el sistema muestre el listado general de articulos. Allí podras buscar los articulos que necesites e inclusive parametrizar dichas busquedas (buscar por descripcion, linea, subgrupo, etc.). Una vez tengas en pantalla los articulos que necesitas podras seleccionar varios articulos y agregarlos simultaneamente.',
    'AYUDA_DESCUENTO_GENERAL'                   => 'Ingresa aquí un valor (porcentaje de descuento) y este se aplicará a todos los articulos del listado de articulos a comprar. Este será el descuento a aplicar a este articulo.',
    'AYUDA_GANANCIA_GENERAL'                    => 'Ingresa aquí un valor (porcentaje de ganancia) y este se aplicará a todos los articulos del listado de articulos a comprar. Este valor será el porcentaje de ganancia del articulo respecto a su precio de compra.',
    'AYUDA_BORRAR_LISTADO_ARTICULOS'            => 'Click aquí para borrar todos los articulos de listado de compras.',
    'AYUDA_VALOR_FLETE'                         => 'Ingresa aquí el valor del flete.',
    'AYUDA_CONCEPTO_DESCUENTO'                  => 'Ingresa aquí el concepto por el cual te realizaron el descuento (Solo ingresar valores si se realizó un descuento).',
    'AYUDA_DESCUENTO'                           => 'Ingresa aquí el valor en porcentaje del descuento (Solo ingresar valores si se realizó un descuento)',
    'AYUDA_MAS_DESCUENTO'                       => 'Haga click aquí si necesita aplicar más descuentos sobre esta factura.',
    'AYUDA_GUIA_SUBTOTAL'                       => 'Aquí aparece el subtotal de la factura.',
    'AYUDA_OBSERVACIONES'                       => 'Ingrese aquí las observaciones correspondientes a esta factura.',
    'AYUDA_IVA'                                 => 'Ingrese aquí el iva total de la factura',
    'AYUDA_LISTADO_ARTICULOS'                   => 'Aquí aparecen los articulos que se van ingresando para la compra. Dispones de diversas opciones en dicho listado, por favor presta mucha atención a todas las ayudas ofrecidas por el sistema.',
    'AYUDA_TOTAL'                               => 'Aquí aparece el total de la factura.',
    'AYUDA_FINALIZAR_FACTURA'                   => 'Click aquí para desplegar el formulario de finalización de la factura.',
    'AYUDA_AGREGAR_VARIOS_ARTICULOS'            => 'Click aquí para mostrar el listado general de<br>articulos y poder agregar varios articulos a la vez.'
);
