<?php
/**
 * @package     FOM
 * @subpackage  Textos Compras
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http://www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 **/
$textos = array(
    /*Basicos*/
    'MODULO_ACTUAL'                             => 'Facturas de Compra',
    'ADICIONAR_ITEM'                            => 'Agregar Factura de Compra',
    'MODIFICAR_ITEM'                            => 'Modificar Factura de Compra',
    'ELIMINAR_ITEM'                             => 'Eliminar Factura de Compra',
    'CONSULTAR_ITEM'                            => 'Consultar Factura de Compra',
    'BUSCAR_ITEM'                               => 'Buscar Factura de Compra',
    'CONFIRMAR_ACCION_FACTURA'                  => 'Qué desea hacer con la Factura de compra N° %1',
    'ACCION_EJECUTADA'                          => 'Acción Ejecutada',
    'GENERAR_FACTURA_COMPRA'                    => 'Generar Factura de Compra',
    'IMPRIMIR_FACTURA_IMPRESORA'                => 'Imprimir Factura en Impresora',
    'IMPRIMIR_FACTURA_POS'                      => 'Imprimir factura POS',
    'FACTURA_GENERADA_EXITOSAMENTE'             => 'Factura generada exitosamente',
    'FACTURA_COMPRA_NUM'                        => 'Factura de compra número:  %1 ',
    'NUMERO_DE_FACTURA'                         => 'Número de Factura',
    'USUARIO_CREADOR'                           => 'Usuario Creador',
    'FECHA_FACTURA'                             => 'Fecha de Factura',
    'USUARIO_QUE_FACTURA'                       => 'Usuario que Factura',
    'NIT'                                       => 'Nit',
    'INFORMACION_FACTURA'                       => 'Información factura',
    'ARCHIVO_FACTURA'                           => 'Archivo factura',
    'FACTURA_DIGITAL'                           => 'Factura digital',
    'CARGAR_FACTURA_DIGITAL_PROVEEDOR'          => 'Click aquí para cargar factura digital',
    'MODIFICAR_ITEM_DESDE_FORMULARIO'           => 'Click aquí para ir al modulo de facturación y editar esta factura',
    'AYUDA_CARGAR_FACTURA_COMPRA_DIGITAL'       => 'Selecciona la factura del proveedor en formato <br> digital (PDF, XLS, XLSX, DOC, DOCX, JPG, PNG)',
    'CARGA_EXITOSA'                             => 'Archivo cargado exitosamente',
    'FALLO_EN_LA_CARGA'                         => 'Hubo una falla al cargar el archivo, actualiza el explorador e intenta de nuevo',
    'FACTURA_DIGITAL_PROVEEDOR'                 => 'Factura digital N° ',
    'GENERAR_FACTURA_DESDE_ORDEN'               => 'Generar factura desde orden de compra',
    'NUM_FACT_PROVEEDOR'                        => '# Fact. Prov.',
    
    'ELIMINAR_FACTURA_DIGITAL'                  => 'Click aquí para eliminar<br> la factura digital',
    'FACTURA_DIGITAL_ELIMINADA'                 => 'Factura digital eliminada correctamente',
    'FALLO_ELIMINAR_FACTURA'                    => 'Fallo al tratar de eliminar la factura digital',
    'MODIFICAR_FACTURA'                         => 'Modificar Factura',
    'MODIFICAR_FECHA_FACTURA'                   => 'Modificar fecha factura',
    'FECHA_MODIFICADA_CORRECTAMENTE'            => 'Fecha modificada correctamente',
    'ERROR_AL_MODIFICAR_FECHA'                  => 'Error, hubo un fallo al tratar de modificar la fecha',
    'SELECCIONE_NUEVA_FECHA_FACTURA'            => 'Seleccione una nueva fecha para la factura de compra',
    
    
    'MENSAJE_FACTURA_TEMPORAL_VENTA'            => 'Tienes una factura de venta sin finalizar realizada el %1',   
    'MENSAJE_FACTURA_TEMPORAL_COMPRA'           => 'Tienes una copia de factura de compra sin finalizar realizada el %1',
    
    /*Campos y labels*/
    'NOMBRE'                                    => 'Nombre',
    'CODIGO'                                    => 'Codigo',
    'NUMERO_FACTURA'                            => 'Factura de Compra N°:',
    'NUMERO_FACTURA_PROVEEDOR'                  => 'Numero Factura del Proveedor',
    'FECHA'                                     => 'Fecha (A-m-d) ',
    'PROVEEDOR'                                 => 'Proveedor ',
    'OBSERVACIONES'                             => 'Observaciones',
    'FECHA_VENCIMIENTO'                         => 'Fecha Vencimiento',
    'LISTA_ARTICULOS'                           => 'Listado de Articulos ',
    'CONCEPTO'                                  => 'Concepto',
    'CUENTA'                                    => 'Cuenta',
    'DEBITO'                                    => 'Débito',
    'REGISTRO_CONTABLE'                         => 'Registro contable',
    'DESCUENTO1'                                => 'Descuento 1 ',
    'DESCUENTO2'                                => 'Descuento 2 ',
    'MAS_DESCUENTO'                             => '+ dcto',
    'ARTICULO'                                  => 'Articulo ',
    'VALOR_FLETE'                               => 'Valor flete',
    'IVA'                                       => 'I.V.A: ',
    'MODO_PAGO'                                 => 'Modo de Pago',
    'MODO_PAGO1'                                => 'Contado',
    'MODO_PAGO2'                                => 'Crédito',
    'CREDITO'                                   => 'Crédito',
    'CONTADO'                                   => 'Contado',
    'VENCIMIENTO'                               => 'Vencimiento (A-m-d): ',
    'TOTAL'                                     => 'Total: ',
    'AGREGAR'                                   => 'Agregar',
    'DESCUENTO_GENERAL'                         => 'Descuento General: ',
    'DESCUENTO'                                 => 'Descuento',
    'SUBTOTAL'                                  => 'Subtotal',
    'REFERENCIA'                                => 'Referencia',
    'FINALIZAR_FACTURA'                         => 'Finalizar Factura',
    'PRECIO_UNITARIO'                           => 'Precio U.',
    'VER_MAS'                                   => 'Click para ver más sobre el item',
    'MOTO'                                      => 'Moto',
    'SUBGRUPO'                                  => 'Subgrupo',
    'GRUPO'                                     => 'Grupo',
    'PRESENTACION'                              => 'Presentacion (empaque)',
    'PLU'                                       => 'Plu',
    'LINEA'                                     => 'Linea',
    'MARCA'                                     => 'Marca',
    'MODELO'                                    => 'Modelo',
    'MEDIDAS'                                   => 'Medidas',
    'CANTIDAD'                                  => 'Cantidad',
    'ID_PROVEEDOR'                              => 'Nit. Proveedor',
    'PRECIO_COMPRA'                             => 'Precio de Compra',
    'PRECIO_COMPRA_ANTERIOR'                    => 'Precio de Compra Anterior',
    'MARGEN_GANANCIA'                           => 'Margen de Ganancia',
    'APLICACION_EXTRA'                          => 'Aplicacion extra',
    'NACIONALIDAD'                              => 'Nacionalidad',
    'MARGEN_GANANCIA_PESOS'                     => 'Margen de Ganancia en Pesos',
    'MARGEN_GANANCIA_PORCENTAJE'                => 'Margen de Ganancia en Procentaje',
    'PRECIO_BASE'                               => 'Precio Venta',
    'LARGO'                                     => 'Largo',
    'ANCHO'                                     => 'Ancho',
    'ALTO'                                      => 'Alto',
    'EL_CODIGO'                                 => 'Codigo: %1',
    'EL_NOMBRE'                                 => 'Nombre: %1',
    'CODIGO_COMERCIAL'                          => 'Codigo comercial',
    'CODIGO_ISO'                                => 'Codigo iso',
    'AYUDA_CODIGO_ISO'                          => 'Codigo iso internacional del pais<br> compuesto por dos letras mayusculas',
    'BANDERA'                                   => 'Bandera',
    'SELECCIONAR_MOTOS_APLICACION'              => 'Seleccione a que motos sirve este articulo',
    'APLICA_SOLO_SU_MOTO'                       => 'Sirve solo a una moto',
    'APLICA_VARIAS_MOTOS'                       => 'Sirve a varias motos',
    'LLEVA_IVA'                                 => 'Lleva iva',
    'NO_LLEVA_IVA'                              => 'No lleva iva',
    'MOTOS_APLICABLE'                           => 'Aplica a las siguientes motos',
    'TEXTO_IVA_1'                               => 'Aplica IVA',
    'TEXTO_IVA_2'                               => 'NO Aplica IVA',
    'APLICABILIDAD_MOTOS'                       => 'Otras motos en que aplica',
    'PRECIOS'                                   => 'Precios',
    'PRECIO'                                    => 'Precio',
    'UBICACION'                                 => 'Ubicación',
    'BODEGA'                                    => 'Bodega',
    'GONDOLA'                                   => 'Gondola',
    'SEDE'                                      => 'Sede',
    'CONCEPTO1'                                 => 'Concepto1',
    'PRECIOS'                                   => 'Precios',
    'PRECIO1'                                   => 'Precio1',
    'CONCEPTO2'                                 => 'Concepto2',
    'PRECIO2'                                   => 'Precio2',
    'CONCEPTO3'                                 => 'Concepto3',
    'PRECIO3'                                   => 'Precio3',
    'CONCEPTO4'                                 => 'Concepto 4',
    'PRECIO4'                                   => 'Precio4',  
    'PRECIO_VENTA1'                             => 'Precio de venta 1',
    'PRECIO_VENTA2'                             => 'Precio de venta 2',
    'PRECIO_VENTA3'                             => 'Precio de venta 3',
    'PRECIO_VENTA4'                             => 'Precio de venta 4',
    'INFORMACION_ARTICULO'                      => 'Información Articulo',
    'INFORMACION_APLICABILIDAD'                 => 'Información de aplicación',
    'INFORMACION_PRECIOS'                       => 'Información precios',
    'INFORMACION_FACTURA'                       => 'Información factura',
    'BUSCAR_FACTURAS'                           => 'Buscar Facturas',
    'FECHA_INICIAL'                             => 'Fecha inicial',
    'FECHA_FINAL'                               => 'Fecha final',
    'AGREGAR_VARIOS_ARTICULOS'                  => 'Agregar multiples articulos',
    'NOTA_DEBITO_DIGITAL_PROVEEDOR'             => 'Nota débito digital proveedor',
    
    /*notas credito*/
    'ADICIONAR_NOTA_CREDITO'                    => '+ nota crédito',
    'ADICIONAR_NOTA_DEBITO'                     => '+ nota debito',
    'INGRESAR_NOTA_CREDITO'                     => 'Ingresar nota crédito',
    'INGRESAR_NOTA_DEBITO'                      => 'Ingresar nota débito',
    'CANTIDAD_A_MODIFICAR'                      => 'Cantidad a modificar',
    'AFECTAR_CANTIDADES_INVENTARIO'             => 'Afectar cantidades inventario',
    'CANTIDAD_DINERO_NOTA'                      => 'Monto dinero nota',
    'CANTIDAD_IVA_NOTA'                         => 'Monto I.V.A nota',
    'CANTIDAD_TOTAL_NOTA'                       => 'Monto total nota',
    'SELECCIONE_FECHA_NOTA'                     => 'Seleccione la fecha en que se expide la nota',
    'CONCEPTO_NOTA'                             => 'Concepto de la nota',
    'FECHA_NOTA'                                => 'Fecha de la nota',
    'CARGAR_NOTA_DIGITAL'                       => 'Cargar copia digital de la nota',
    'AYUDA_CARGAR_NOTA_CREDITO'                 => 'Seleccione la nota crédito expedida por el proveedor<br>para guardar una copia del archivo digital.',    
    'NOTA_CREDITO_ADICIONADA_A_FACTURA'         => 'Nota crédito adicionada exitosamente',
    'AYUDA_CARGAR_NOTA_DEBITO'                  => 'Seleccione la nota débito expedida por el proveedor<br>para guardar una copia del archivo digital.',    
    'NOTA_CREDITO_ADICIONADA_A_FACTURA'         => 'Nota débito adicionada exitosamente',    
    'NOTAS_CREDITO'                             => 'Notas crédito',
    'NOTAS_DEBITO'                              => 'Nota débito',
    'ID_FACTURA'                                => 'Id de la factura',
    'TOTAL_NOTA'                                => 'Total nota',
    'NOTA_DIGITAL'                              => 'Nota digital',
    'CONSULTAR_NOTA_CREDITO'                    => 'Consultar nota credito',
    'CANTIDAD_ANTERIOR'                         => 'Cantidad anterior',
    'CANTIDAD_NUEVA'                            => 'Cantidad nueva',
    'ELIMINAR_NOTA_DIGITAL'                     => 'Eliminar nota digital',
    'NOTA_DIGITAL_ELIMINADA'                    => 'Nota digital eliminada',
    'NOTA_CREDITO_DIGITAL_PROVEEDOR'            => 'Nota crédito digital',
    'CONSULTAR_NOTA_DEBITO'                     => 'Consultar nota debito',
    
    
    'ERROR_FALTA_MONTO_NOTA'                    => 'Error, falta el monto de la nota',
    'ERROR_FALTA_IVA_NOTA'                      => 'Error, falta el iva de la nota',
    'ERROR_FALTA_TOTAL_NOTA'                    => 'Error, falta el total de la nota',
    'ERROR_FALTA_CONCEPTO_NOTA'                 => 'Error, falta el concepto de la nota',
    
    
    /*Errores*/
    'ERROR_FALTA_CODIGO'                        => 'Error falta codigo',
    'ERROR_EXISTE_CODIGO'                       => 'Error existe un pais con este codigo iso',
    'ERROR_EXISTE_CODIGO_COMERCIAL'             => 'Error existe un pais con este codigo comercial',
    'ERROR_FALTA_NOMBRE'                        => 'Error falta nombre', 
    'ERROR_EXISTE_NOMBRE'                       => 'Error existe un articulo registrado con ese nombre',
    'ERROR_FORMATO_CODIGO'                      => 'Error formato codigo iso, solo deben ser dos letras mayusculas',
    'ERROR_FORMATO_NOMBRE'                      => 'Error formto nombre, deben ser solo letras',
    'ERROR_FALTA_SUBGRUPO'                      => 'Error falta subgrupo',
    'ERROR_SUBGRUPO_INEXISTENTE'                => 'Error, debe seleccionar un subgrupo de la lista',
    'ERROR_FALTA_GRUPO'                         => 'Error falta grupo',
    'ERROR_GRUPO_INEXISTENTE'                   => 'Error, debe seleccionar un grupo de la lista',    
    'ERROR_MOTO_INEXISTENTE'                    => 'Error, debe seleccionar una moto de la lista',
    'ERROR_PAIS_INEXISTENTE'                    => 'Error, debe seleccionar un pais de la lista',
    'ERROR_UNIDAD_INEXISTENTE'                  => 'Error, debe seleccionar una unidad de la lista',
    'ERROR_MARCA_INEXISTENTE'                   => 'Error, debe seleccionar una marca de la lista',
    'ERROR_FALTA_REFERENCIA'                    => 'Error, falta referencia',
    'ERROR_FALTA_UNIDAD'                        => 'Error, falta unidad',
    'ERROR_FALTA_PAIS'                          => 'Error, falta pais',
    'ERROR_FALTA_PRECIO_BASE'                   => 'Error, debes introducir almenos un precio de venta',
    'ERROR_FALTA_PRECIO_COMPRA'                 => 'Error, falta precio compra',
    'ERROR_FALTA_MARGEN_GANANCIA'               => 'Error, falta margen ganancia',
    'ERROR_FECHA_VACIA'                         => 'Error, debes ingresar un valor de fecha valido',
    'FALLO_ELIMINAR_NOTA'                       => 'Error, Fallo al eliminar la nota',
    
    /*Ayuda*/
   
    'AYUDA_MODULO'                              => '<p>* F1 Para agregar varios articulos al tiempo </p><p>* F2 Para buscar facturas  </p><p>* Shift + M para cerrar el menu superior.</p><p><p class = \'videotutorialAyuda\'>* <a onclick=\'cerrarAyuda()\' rel=\'prettyPhoto[]\' href=\'http://www.youtube.com/watch?v=x6UODla2hqE\' target=\'blank\'>Click Aqui para ver video de ayuda paso a paso</a></p>*Para cerrar esta ventana presione Ctrl+H, o haga click en cualquier lugar <br>'
);
