<?php

/**
 *
 * @package     FOLCS
 * @author      Francisco J. Lozano B. <fjlozano@felinux.com.co>
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http://www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 *
 **/

$textos = array(
    /**
     *
     * Página de inicio y elementos fijos de la plantilla
     *
     **/
    'BUSCAR'                            => 'Buscar',
    'PRIMERA_PAGINA'                    => 'Primera',
    'ULTIMA_PAGINA'                     => 'Última',
    'PAGINA_ANTERIOR'                   => 'Atrás',
    'PAGINA_SIGUIENTE'                  => 'Adelante',
    'TEXTO_BUSCADOR'                    => 'buscar...',
    'TEXTO_ESPERA'                      => 'Por Favor Espere  ...',
    'USUARIO'                           => 'Usuario',
    'CONTRASENA'                        => 'Contraseña',
    'INICIAR_SESION'                    => 'Iniciar Sesión',
    'RECORDAR_CONTRASENA'               => 'Olvido la contraseña?',
    'CONTRASENA_ENVIADA'                => 'Tu nueva contraseña fue enviada a tu e-mail',
    'REGISTRARSE'                       => 'Registrarse',
    'CONFIRMAR_CONTRASENA'              => 'Confirmar Contraseña',
    'APELLIDOS'                         => 'Apellidos',
    'NOMBRES'                           => 'Nombres',
    'CORREO'                            => 'e-mail',
    'PAGINA_WEB'                        => 'Pagina Web',
    'BANNER'                            => 'Publicidad',
    'SIN_CONTENIDO'                     => 'No hay contenido que mostrar. Regresa Pronto.',
    'ENLACE'                            => 'Enlace',
    'MODULO'                            => 'Modulo',
    'MODULOS'                           => 'Modulos',
    'VER_MAS'                           => 'Ver más',
    'SOLO_NUMEROS'                      => 'Introduce solo numeros',
    'CONTACTOS_CONECTADOS'              => 'Contactos en Linea (0)',
    'CHAT'                              => 'Chat',
    'AYUDA'                             => 'Ayuda<br>Ctrl+H',
    'VIDEOS'                            => 'Video',
    'ENLACE_AL_VIDEO'                   => 'Enlace',
    'FOROS'                             => 'Foros',
    'ENCUESTA'                          => 'Encuesta',
    'ENCUESTAS'                         => 'Encuestas',
    'BOTON_VOTAR'                       => 'Votar',
    'SIGANOS'                           => 'Siganos en ',
    'FOTOS'                             => 'Imagenes',
    'COMENTAR'                          => 'Comentar',
    'COMENTARIO'                        => 'Comentario',
    'COMENTARIOS'                       => 'Comentarios',
    'USUARIO_DIJO'                      => ' dijo:',
    'USUARIO_DICE'                      => ' dice:',
    'PUBLICADO_POR'                     => 'Publicado por %1',
    'PUBLICADO_EN'                      => 'Publicado en%1',
    'CREADO_POR'                        => 'Creado por %1',
    'CREADO_POR2'                       => 'por %1',
    'PAIS'                              => 'Pais',
    'PLU'                               => 'Plu',
    'CIUDAD'                            => 'Ciudad',
    'GENERO'                            => 'Genero',
    'GENERO_M'                          => 'Hombre',
    'GENERO_F'                          => 'Mujer',
    'MASCULINO'                         => 'Masculino',
    'FEMENINO'                          => 'Femenino',
    'FECHA_NACIMIENTO'                  => 'Fecha Nacimiento',
    'NOMBRE'                            => 'Nombre',
    'DESPUES_DE'                        => 'Despues de',
    'IMAGEN'                            => 'Imagen',
    'MENU'                              => 'Menú',
    'TITULO'                            => 'Título',
    'DESCRIPCION'                       => 'Descripción',
    'CONTENIDO'                         => 'Contenido',
    'PALABRAS_CLAVES'                   => 'Palabras Clave',
    'URL'                               => 'URL',
    'ARCHIVO'                           => 'Archivo',
    'DESTINO'                           => 'Destino',
    'ACTIVO'                            => 'Activo',
    'INACTIVO'                          => 'Inactivo',
    'FECHA_CREACION'                    => 'Creado',
    'FECHA_PUBLICACION'                 => 'Publicado',
    'FECHA_ACTUALIZACION'               => 'Actualizado',
    'AUTOR'                             => 'Autor',
    'ESTADO'                            => 'Estado',
    'DE'                                => 'de',
    'MI_PERFIL'                         => 'My perfil',
    'NOTIFICACIONES'                    => 'Notificaciones',
    'MENSAJES'                          => 'Mensajes',
    'RESTAURAR_CONSULTA'                => '<span class=margenDerechaTriple>Click para restaurar la consulta global</span>',
    'BUSCAR_ITEM'                       => '<span class=margenDerechaTriple>Click para buscar</span>',
    'ESCRIBA_NOMBRE_MODULO'             => 'Escriba el nombre del modulo al cual desea ir',
    'BUSCAR_MODULOS'                    => 'Buscar Modulos',
    'EFECTIVO'                          => 'Efectivo',
    'TARJETA'                           => 'Tarjeta',
    'CHEQUE'                            => 'Cheque',
    'MEDIOS_PAGO'                       => 'Medios de pago',
    'RETENCIONES'                       => 'Retenciones',
    'RETEFUENTE'                        => 'Retefuente',
    'REGIMEN_SIMPLIFICADO'              => 'Regimen Simplificado',
    'REGIMEN_COMUN'                     => 'Regimen Común',
    'GRAN_CONTRIBUYENTE'                => 'Gran Contribuyente',
    'GRAN_CONTRIBUYENTE_AUTORETENEDOR'  => 'Gran Contribuyente autoretenedor',
    'SIMPLIFICADO_NO_RESIDENTE'         => 'Simplificado no residente',
    'NO_RESIDENTE'                      => 'No residente',
    'EMPRESA_DEL_ESTADO'                => 'Empresa del estado',
    'NO_RESPONSABLE'                    => 'No responsable',
    'REGIMEN_1'                         => 'Regimen simplificado',
    'REGIMEN_2'                         => 'Regimen Común',
    'REGIMEN_3'                         => 'Gran Contribuyente',
    'REGIMEN_4'                         => 'Gran Contribuyente autoretenedor',
    'REGIMEN_5'                         => 'Simplificado no residente',
    'REGIMEN_6'                         => 'No residente',
    'REGIMEN_7'                         => 'Empresa del estado',
    'REGIMEN_8'                         => 'No responsable',
    
    'VENCIMIENTO_FACTURA_COMPRA'        => 'Vencimiento Fact. Compra.',
    'VENCIMIENTO_FACTURA_VENTA'         => 'Vencimiento Fact. Venta.',
    
    'DESCRIPCION_VTO_FC'                => 'Tienes una factura de compra por pagar al proveedor %1.',
    'DESCRIPCION_VTO_FV'                => 'Tienes una factura de venta por cobrar al cliente %1.',
    
    'ELIMINAR_MASIVO'                   => 'Eliminar varios',
    'CONFIRMAR_ELIMINACION_VARIOS'      => 'Seguro que desea eliminar estos %1 registros',
    'ELIMINAR_VARIOS_REGISTROS'         => 'Eliminar varios registros',
    'ITEMS_ELIMINADOS_CORRECTAMENTE'    => 'Se han eliminado los registros correctamente',
    'MARCAR_FILAS'                      => 'Marcar todas las filas',
    'AYUDA_MARCAR_FILAS'                => 'Click aquí para marcar todas las filas de la tabla',
  
    'SIN_ARCHIVOS'                      => 'No hay documentos guardados',
    'SIN_IMAGENES'                      => 'No hay imagenes guardadas',
    'NO_HA_SELECCIONADO_ITEM'           => 'Ha ocurrido un error, o bien ya no existe el item que desea seleccionar, o no ha seleccionado ninguno',
    'SIN_REGISTROS'                     => 'No hay registros',
    'DIRECCION'                         => 'Dirección',
    'TELEFONO'                          => 'Teléfono',
    'TELEFONOS'                         => 'Teléfonos',
    'TELEFONO_PRINCIPAL'                => 'Teléfono Principal',
    'TELEFONO_SECUNDARIO'               => 'Teléfono Secundario',
    'CELULAR'                           => 'Celular',
    'LATITUD'                           => 'Latitud',
    'LONGITUD'                          => 'Longitud',
    'CONTROL_ACCESO'                    => 'Control de Acceso',
    'RESULTADOS_BUSQUEDA'               => 'Tu busqueda trajo %1 resultados',
    'QUE_HA_PASADO'                     => 'Novedades', 
    'PUBLICO'                           => 'Publico',
    'PRIVADO'                           => 'Privado',
    'DESCONECTAR_CHAT'                  => 'Aparecer desconectado',
    'CONECTAR_CHAT'                     => 'aparecer conectadoe',
    'PERFIL_ACTUAL'                     => 'Perfil actual',
    'SIN_CIUDAD'                        => 'No ha seleccionado ciudad de residencia',
    'POR_FAVOR_ESCOJA_CIUDAD'           => 'Por favor seleccione su ciudad de residencia',
    'SELECCIONAR'                       => 'Seleccionar',
    'DIA'                               => 'Día',
    'SEMANA'                            => 'Semana',
    'MES'                               => 'Mes',
    'ANYO'                              => 'Año',
    'DIAS'                              => 'Días',
    'SEMANAS'                           => 'Semanas',
    'MESES'                             => 'Meses',
    'TRES_MESES'                        => 'Tres Meses',
    'SEIS_MESES'                        => 'Seis Meses',
    'ANYOS'                             => 'Años',
    'UNO'                               => 'Uno',
    'DOS'                               => 'Dos',
    'TRES'                              => 'Tres',
    'CUATRO'                            => 'Cuatro',
    'CINCO'                             => 'Cinco',
    'SEIS'                              => 'Seis',
    'SIETE'                             => 'Siete',
    'OCHO'                              => 'Ocho',
    'NUEVE'                             => 'Nueve',
    'DIEZ'                              => 'Diez',
    /**
     *
     * Módulos
     *
     **/
    'INICIO'                            => 'Home',
    'ERROR'                             => 'Error',
    'PAISES'                            => 'Paises',
    'ESTADOS'                           => 'Estados',
    'CIUDADES'                          => 'Ciudades',
    'PERFILES'                          => 'Perfiles',
    'USUARIOS'                          => 'Usuarios',
    'CHAT'                              => 'Chat',
    'MENUS'                             => 'Menus',
    'PAGINAS'                           => 'Paginas',
    'CATEGORIAS'                        => 'Categorias',
    'NOTICIAS'                          => 'Noticias',
    'CONFIGURACIONES'                   => 'Configuraciones',
    'ANUNCIOS'                          => 'Publicidad',
    'CONTACTOS'                         => 'Contactos',
    'FINALIZAR'                         => 'Cerrar Sesión',
    'EVENTOS'                           => 'Eventos',
    'PRIVILEGIOS'                       => 'Privilegios',
    'GRUPOS'                            => 'Grupos',
    'ACTIVIDADES'                       => 'Actividades',
    'IMAGENES'                          => 'Imagenes',
    'DOCUMENTOS'                        => 'Documentos',
    'FACTURAS_TEMPORALES_COMPRA'        => 'Facturas temporales compra',
    'FACTURAS_TEMPORALES_VENTA'         => 'Facturas temporales venta',
    'FACTURAS_COMPRA'                   => 'Facturas compra',
    'FACTURAS_VENTA'                    => 'Facturas venta',    
    'COTIZACIONES'                      => 'Cotizaciones',
    'ORDENES_COMPRA'                    => 'Ordenes compra',  
    'PROVEEDORES'                       => 'Proveedores',
    'ARTICULO_INVENTARIO'               => 'Registros en inventario',
    'MOVIMIENTOS_MERCANCIA_ARTICULO'    => 'Registros de movimiento de mercancia',
    'MOTOS'                             => 'Motos',
    'ACTIVIDAD_ECONOMICA'               => 'Actividad economica',
    
    /**
     *
     * Operaciones
     *
     **/
    'RESPONDER'                         => 'Responder',
    'ACEPTAR'                           => 'Aceptar',
    'CONSULTAR'                         => 'Consultar',
    'MODIFICAR'                         => 'Editar',
    'ELIMINAR'                          => 'Borrar',
    'APROBAR'                           => 'Aprovar',
    'SUBIR'                             => 'Subir',
    'BAJAR'                             => 'Bajar',
    'SOLO_PUEDES_TENER_MAXIMO_5_PAGINAS' => 'Solo puedes tener 5 paginas, modifica o elimina alguna de las que existen para poder agregar nuevo contenido',
    'CONFIRMAR_ELIMINACION'             => 'Esta seguro que desea borrar %1?',
    'GESTIONAR_INFORMACION_DE'          => 'Puedes -Editar-  o  -Eliminar-  a:  %1',
    'GESTIONAR_INFORMACION'             => 'Gestion de informacion',
    'ADICIONAR_ARCHIVO'                 => 'Agregar documento',
    'ADICIONAR_IMAGEN'                  => 'Agregar imagen',
    'PAGINACION'                        => 'registro %1 al %2 de %3',
    'MODIFICAR_PERFIL'                  => 'Modify Profile',
    'REGISTRO_AGREGADO'                 => 'Registro Agregado Exitosamente',
    'REGISTRO_MODIFICADO'               => 'Registro Modificado Exitosamente',
    'REGISTRO_ELIMINADO'                => 'Registro Eliminado Exitosamente',
    'DESLICE_LA_BARRA'                  => 'Por favor mueva la barra a la derecha',
    'AGREGAR_VARIOS_ARTICULOS'          => 'Agregar varios articulos',
    'HERRAMIENTAS_DE_OPERACION'         => 'Herramientas de operación',
    'MOSTRAR_CALCULADORA'               => 'Mostrar calculadora<br> (Ctrl + F2)',
    'ID_AUTOMATICO'                     => 'Id. automático',
    'ADICIONAR_MASIVO'                          => 'Subir Archivo',    
    'ARCHIVO_MASIVO'                            => 'Archivo',
    'INFORMACION_ARCHIVO'                       => 'Información de archivo',
    'AYUDA_INFORMACION_ARCHIVO'                 => 'Ayuda',
    'CAMPO_BASE_DATOS'                          => 'Campo base de datos',
    'CAMPO_ARCHIVO'                             => 'Campo archivo',
    'CARGAR'                                    => 'Cargar',
    'COMPLETO'                                  => 'Completo',
    'COMPLETO_1'                                => 'Si',
    'COMPLETO_0'                                => 'No',
    'MASIVO_CARGADO_CORRECTAMENTE'              => 'Información cargada correctamente!!!',
    'INDICACIONES_ARCHIVO_MASIVO_1'             => 'Por favor, asegurese que el archivo sea de extensión [xls]<br />',
    'INDICACIONES_ARCHIVO_MASIVO_2'             => 'Que contenga los encabezados en la primera fila [1] y los datos inicien desde la primera columna [A]<br />Evite filas completas en blanco entre los datos a cargar<br />',
    /**
     *
     * Mensajes de error
     *
     **/
    'BUSQUEDA_SIN_RESULTADOS'           => 'Busqueda sin resultados',
    'ERROR_FALTA_NOMBRE'                => 'Por favor ingrese un nombre',
    'ERROR_FORMATO_IMAGEN'              => 'Error formato imagen, debe ser png o jpeg',
    'ERROR_FALTA_ARCHIVO'               => 'Por favor, escoja un archivo para realizar la importación de los datos',
    'ERROR_FALTA_CADENA_BUSQUEDA'       => 'Debe introducir un texto para buscar',
    'ERROR_TAMAÑO_CADENA_BUSQUEDA'      => 'Para buscar debe ingresar al menos %1 caracter(es)',
    'MENSAJE_TAMANO_ARCHIVO'            => 'Max. tamaño (%1)',
    'ERROR_MODULO_INEXISTENTE'          => 'Error, modulo inexistente',
    'ERROR_DESCONOCIDO'                 => 'Ha ocurrido un error no identificado al procesar los datos, por favor recargue la aplicacion e intente de nuevo',
    'MAXIMO_TEXTO_250'                  => 'Su mensaje puede tener maximo 250 caracteres.',
    'MAXIMO_TEXTO_511'                  => 'Su mensaje puede tener maximo 511 caracteres.',
    'ERROR_EXISTE_CODIGO'               => 'Error ya existe un item con ese codigo',
    'ERROR_EXISTE_NOMBRE'               => 'Error ya existe un item con ese nombre',
    'SIN_PERMISOS_ACCESO_MODULO'        => 'No tienes permiso para acceder a este modulo',
    'BUSQUEDA_SIN_RESULTADOS'           => 'Tu busqueda no tuvo resultados',
    'NUMERO_FILAS'                      => 'N° filas',
    'CODIGO_DE BARRA_GENERADO_EXITOSAMENTE' => 'Código de barra generado exitosamente',
    'MODULO_SIN_REGISTROS'              => 'No se ha encontrado registros',
    'ERROR_FORMATO_ARCHIVO'             => 'Error, formato de archivo invalido.',
    'ERROR_DEBE_LLENAR_TODOS_LOS_CAMPOS_DEL_FORMULARIO' => 'Error, debe de llenar todos los campos del formulario.',
    'FORMATO_ARCHIVO_INVALIDO'          => 'Error, formato de archivo invalido',
    
    'TEXTO_NUMERICO_DE_X_CARACTERES'    => 'Debe introducir numeros y maximo <br>  %1 caracter(es)',
    'TEXTO_CODIGO_INTERNO'              => 'Escriba un codigo corto para %1',
    'AYUDA_USO_AUTOCOMPLETAR'           => 'Escriba al menos una letra <br> y seleccione una opcion de la lista',
    'AYUDA_SELECCIONAR_CANTIDAD_REGISTROS'      => 'Ingresa la cantidad de registros<br> que deseas ver y presiona ENTER',
    'AYUDA_ASCENDENTE'                  => 'Click para organizar<br>de manera ASCendente',
    'AYUDA_DESCENDENTE'                  => 'Click para organizar<br>de manera DESCendente',
);

?>