<?php

/**
 *
 * @package     FOLCS
 * @subpackage  Textos Articulos
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http://www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 *
 **/

$textos = array(
    /*Basicos*/
    'MODULO_ACTUAL'                             => 'Inventario',
    'ADICIONAR_ITEM'                            => 'Agregar Articulo',
    'MODIFICAR_ITEM'                            => 'Modificar Modificar',
    'ELIMINAR_ITEM'                             => 'Eliminar Articulo',
    'CONSULTAR_ITEM'                            => 'Consultar Inventario',
    'BUSCAR_ITEM'                               => 'Buscar Articulo',
    'BUSCAR_ARTICULOS_TABLA'                    => 'Buscar Articulos <br> S = Subgrupo, L = Linea',
    'ADD_CAMPO_MARCA'                           => '+ marca a busqueda',
    'AYUDA_AGREGAR_MARCA'                       => 'Click aquí para mostrar el campo de <br>busqueda por marca y agregar la marca <br>del articulo a la busqueda',
    'BUSCAR_ARTICULOS'                          => 'Buscar Articulos',
    'BUSCAR_POR_MARCA'                          => 'Agregar la marca del articulo a la busqueda',
    'PATRON_BUSQUEDA'                           => 'Ingresa el texto que deseas buscar',
    'SELECCIONE_PATRON_BUSQUEDA'                => 'Seleccione por que desea buscar',
    'AYUDA_SELECCIONAR_ITEMS_TABLA'             => 'flecha arriba/abajo = moverse  /  F5 = seleccionar fila  / F9 = consultar articulo / F6 = des-seleccionarla / Enter = finalizar / Esc = Salir',
    /*Campos y labels*/
    'NOMBRE'                                    => 'Descripción',
    'ID_ARTICULO'                               => 'Id articulo',
    'CODIGO'                                    => 'Codigo',
    'PAIS'                                      => 'Pais',
    'REFERENCIA'                                => 'Referencia',
    'PLU_INTERNO'                               => 'PLU interno',
    'MOTO'                                      => 'Moto',
    'SUBGRUPO'                                  => 'Subgrupo',
    'GRUPO'                                     => 'Grupo',
    'PRESENTACION'                              => 'Presentacion (empaque)',
    'PLU'                                       => 'Plu',
    'LINEA'                                     => 'Linea',
    'MARCA'                                     => 'Marca',
    'MODELO'                                    => 'Modelo',
    'MEDIDAS'                                   => 'Medidas (en cm.)',
    'CANTIDAD'                                  => 'Cantidad',
    'PRECIO_COMPRA'                             => 'Precio de Compra',
    'PRECIO_COMPRA_ANTERIOR'                    => 'Precio de Compra Anterior',
    'MARGEN_GANANCIA'                           => 'Margen de Ganancia',
    'APLICACION_EXTRA'                          => 'Aplicacion extra',
    'NACIONALIDAD'                              => 'Nacionalidad',
    'MARGEN_GANANCIA_PESOS'                     => 'Margen de Ganancia en Pesos',
    'MARGEN_GANANCIA_PORCENTAJE'                => 'Margen de Ganancia en Procentaje',
    'PRECIO_BASE'                               => 'Precio Venta',
    'LARGO'                                     => 'Largo',
    'ANCHO'                                     => 'Ancho',
    'ALTO'                                      => 'Alto',
    'CODIGO_COMERCIAL'                          => 'Codigo comercial',
    'CODIGO_ISO'                                => 'Codigo iso',
    'AYUDA_CODIGO_ISO'                          => 'Codigo iso internacional del pais<br> compuesto por dos letras mayusculas',
    'BANDERA'                                   => 'Bandera',
    'SELECCIONAR_MOTOS_APLICACION'              => 'Seleccione a que motos sirve este articulo',
    'APLICA_SOLO_SU_MOTO'                       => 'Sirve solo a una moto',
    'APLICA_VARIAS_MOTOS'                       => 'Sirve a varias motos',
    'LLEVA_IVA'                                 => 'Lleva iva',
    'NO_LLEVA_IVA'                              => 'No lleva iva',
    'MOTOS_APLICABLE'                           => 'Aplica a las siguientes motos',
    'TEXTO_IVA_1'                               => 'Aplica IVA',
    'TEXTO_IVA_2'                               => 'NO Aplica IVA',
    'APLICABILIDAD_MOTOS'                       => 'Otras motos en que aplica',
    'PRECIOS'                                   => 'Precios',
    'CONCEPTO'                                  => 'Ingrese el concepto del precio',
    'PRECIO'                                    => 'Precio',
    'UBICACION'                                 => 'Ubicación',
    'BODEGA'                                    => 'Bodega',
    'GONDOLA'                                   => 'Gondola',
    'CODIGO_OEM'                                => 'Codigo OEM',
    'ID_AUTOMATICO'                             => 'Id Auto.',
    'SEDE'                                      => 'Sede',
    'CONCEPTO1'                                 => 'Concepto1',
    'PRECIO_MOSTRADOR'                          => 'Precio de mostrador',    
    'PRECIO_MAYOR'                              => 'Precio al por mayor', 
    'PRECIOS'                                   => 'Precios',
    'PRECIO1'                                   => 'Precio1',
    'CONCEPTO2'                                 => 'Concepto2',
    'PRECIO2'                                   => 'Precio2',
    'CONCEPTO3'                                 => 'Concepto3',
    'PRECIO3'                                   => 'Precio3',
    'CONCEPTO4'                                 => 'Concepto 4',
    'PRECIO4'                                   => 'Precio4',  
    'PRECIO_VENTA'                              => 'Precio Venta',
    'PRECIO_VENTA1'                             => 'Precio de venta 1',
    'PRECIO_VENTA2'                             => 'Precio de venta 2',
    'PRECIO_VENTA3'                             => 'Precio de venta 3',
    'PRECIO_VENTA4'                             => 'Precio de venta 4',
    'INFORMACION_ARTICULO'                      => 'Información Articulo',
    'INFORMACION_APLICABILIDAD'                 => 'Información de aplicación',
    'INFORMACION_PRECIOS'                       => 'Información precios',
    'CODIGO_DE_BARRAS'                          => 'Codigo de Barras',
    'BUSCAR_FACTURAS'                           => 'Buscar Facturas',
    'IMAGEN1'                                   => 'Imágen 1',
    'IMAGEN2'                                   => 'Imágen 2',
    'TODOS_LOS_ARTICULOS'                       => 'Mostrar todos los articulos',
    'INFORMACION_INVENTARIO'                    => 'Información existencias',
    'IMPRIMIR_VARIOS_BARCODES'                  => 'Imp. Códigos de Barra',
    'CONFIRMAR_IMPRIMIR_VARIOS'                 => 'Esta seguro que desea imprimir los códigos de barra de estos %1 articulo(s)?',
    'MOVER_MERCANCIA'                           => 'Mover Mercancia',
    'ARTICULO'                                  => 'Articulo',
    'BODEGA_ORIGEN'                             => 'Bodega de Origen',
    'BODEGA_DESTINO'                            => 'Bodega de Destino',
    'SELECCIONAR'                               => 'Seleccionar',
    'NO_EXISTENCIAS_NO_MOVIMIENTOS'             => 'No hay existencias en ninguna bodega, así que no puedes realizar movimientos de mercancia sobre este articulo.',
    'SELECCIONA_ORIGEN'                         => 'Selecciona una bodega de origen',
    'CANTIDAD_A_MOVER'                          => 'Ingrese la cantidad que desea mover',
    'RESTAURAR'                                 => 'Reset',
    'CODIGO_DE BARRA_GENERADO_EXITOSAMENTE'     => 'Codigo de barra generado exitosamente',
    'IMPRIMIR_VARIOS_BARCODE'                   => 'Imprimir varios codigos de barras',
    'CANTIDAD_A_IMPRIMIR'                       => 'Cantidad de códigos de barra a imprimir',
    'CLICK_EN_ICONO'                            => 'y click en ícono',
    'INFORMACION_ECONOMICA_ARTICULO'            => 'Información económica',
    'ULTIMO_PRECIO_COMPRA'                      => 'Último precio compra',
    'PRECIO_PROMEDIO_COMPRA'                    => 'Precio promedio de compra en los últimos %1 días',
    'STOCK_MINIMO'                              => 'Stock mín.',
    'STOCK_MAXIMO'                              => 'Stock máx.',
    'KARDEX'                                    => 'Kardex',
    'FECHA_INICIAL'                             => 'Fecha inicial',
    'FECHA_FINAL'                               => 'Fecha final',
    'CONSULTAR_KARDEX'                          => 'Consultar kardex',
    'FECHA'                                     => 'Fecha',
    'ENTRADA'                                   => 'Entrada',
    'SALIDA'                                    => 'Proveedor',
    'CANTIDAD'                                  => 'Cantidad',
    'PROVEEDOR'                                 => 'Proveedor',
    'GRAVADO_IVA'                               => 'Gravado iva',
    'ARTICULO_NO_GRAVADO'                       => '<span class=negrilla>IVA:</span> Sin gravamen',
    'FILTRAR_POR_BODEGA'                        => 'Filtrar por bodega',

    
    
    /*Errores*/
    'ERROR_FALTA_CODIGO'                        => 'Error falta codigo',
    'ERROR_EXISTE_CODIGO'                       => 'Error existe un pais con este codigo iso',
    'ERROR_EXISTE_CODIGO_COMERCIAL'             => 'Error existe un pais con este codigo comercial',
    'ERROR_FALTA_NOMBRE'                        => 'Error falta Descripcion', 
    'ERROR_EXISTE_NOMBRE'                       => 'Error existe un articulo registrado con esa descripción',
    'ERROR_FORMATO_CODIGO'                      => 'Error formato codigo iso, solo deben ser dos letras mayusculas',
    'ERROR_FORMATO_NOMBRE'                      => 'Error formato descripción, deben ser solo letras',
    'ERROR_FALTA_SUBGRUPO'                      => 'Error falta subgrupo',
    'ERROR_SUBGRUPO_INEXISTENTE'                => 'Error, debe seleccionar un subgrupo de la lista',
    'ERROR_FALTA_GRUPO'                         => 'Error falta grupo',
    'ERROR_GRUPO_INEXISTENTE'                   => 'Error, debe seleccionar un grupo de la lista',    
    'ERROR_MOTO_INEXISTENTE'                    => 'Error, debe seleccionar una moto de la lista',
    'ERROR_PAIS_INEXISTENTE'                    => 'Error, debe seleccionar un pais de la lista',
    'ERROR_UNIDAD_INEXISTENTE'                  => 'Error, debe seleccionar una unidad de la lista',
    'ERROR_MARCA_INEXISTENTE'                   => 'Error, debe seleccionar una marca de la lista',
    'ERROR_FALTA_REFERENCIA'                    => 'Error, falta referencia',
    'ERROR_FALTA_UNIDAD'                        => 'Error, falta unidad',
    'ERROR_FALTA_PAIS'                          => 'Error, falta pais',
    'ERROR_FALTA_PRECIO_BASE'                   => 'Error, debes introducir almenos un precio de venta',
    'ERROR_FALTA_PRECIO_COMPRA'                 => 'Error, falta precio compra',
    'ERROR_FALTA_MARGEN_GANANCIA'               => 'Error, falta margen ganancia',
    'ERROR_LINEA_INEXISTENTE'                   => 'Error, debe seleccionar una linea de la lista',
    'ERROR_FALTA_CODIGO_OEM'                    => 'Error, Falta el codigo OEM',
    'ERROR_FORMATO_IMAGEN'                      => 'Error formato de archivo (xls, xlsx)',
    'ERROR_FALTAN_DATOS'                        => 'Error, debe asignar por lo menos los campos PLU interno y Descripción',
    'ADICIONAR_ARTICULOS_FACTURA'               => 'Click para adicionar los <br>articulos a la factura.',
    
    /*Ayuda*/
    'AYUDA_CODIGO_COMERCIAL'                    => 'Codigo comercial del pais<br>Ejemplo: Taiwan TAW',
    'AYUDA_CODIGO_OEM'                          => 'Código internacional, es el<br> código de "Original Equipment Manufacturer',
    'AYUDA_REFERENCIA'                          => 'Código con el que llega el articulo, <br>es el código de barras',
    'AYUDA_MOVER_MERCANCIA_1'                   => 'Primero, seleccionar la bodega de destino',
    'AYUDA_MOVER_MERCANCIA_2'                   => 'Segundo, Seleccionar la bodega de origen',
    'AYUDA_MOVER_MERCANCIA_3'                   => 'Tercero, ingresar la cantidad que desea mover',
    'AYUDA_CANTIDAD_BARCODE_A_IMPRIMIR'         => 'Ingresa la cantidad de códigos que<br>deseas imprimir, y haz click en el icono',
    'AYUDA_DESCRIPCION_ARTICULO'                => 'Ingresa la descripción del articulo',
    'AYUDA_MOVER_MERCANCIA_4'                   => 'Cuarto, hacer click en aceptar',
    'AYUDA_RESTAURAR_VALORES'                   => 'Click aqui para poner todos los campos vacios',
    'AYUDA_IVA'                                 => 'Ingrese el valor del I.V.A<br> para este articulo',
    'AYUDA_GRAVADO_IVA'                         => 'Marque esta casilla para determinar<br>si el articulo esta gravado con IVA',
    'AYUDA_STOCK_MINIMO'                        => 'Ingrese el stock minimo <br> para este articulo',
    'AYUDA_STOCK_MAXIMO'                        => 'Ingrese el stock maximo <br> para este articulo',
    'AYUDA_IMPRIMIR_CODIGO_BARRAS_PDF'          => 'Click aquí para imprimir el<br> código de barras en PDF',    
    'AYUDA_AGREGAR_MOTOS_APLICACION'            => '* Escriba el nombre de la moto que desea agregar.<br>* Seleccionela de la lista. <br>* Puede agregar tantas motos como desee. <br>* La primera moto será la moto principal del articulo.',
    'AYUDA_PANEL_MOTOS_APLICACION'              => 'Puede arrastrar y soltar las motos del panel.<br>Así mismo puede eliminarlas haciendo click<br>en el boton X de la derecha de cada moto',
);
