<?php
/**
 * @package     FOM
 * @subpackage  Ordenes Compras
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http://www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 **/
$textos = array(
    /*Basicos*/
    'MODULO_ACTUAL'                             => 'Ordenes de Compra (Cotización de Compra)',
    'ADICIONAR_ITEM'                            => 'Agregar Orden de Compra',
    'MODIFICAR_ITEM'                            => 'Modificar Orden de Compra',
    'ELIMINAR_ITEM'                             => 'Eliminar Orden de Compra',
    'CONSULTAR_ITEM'                            => 'Consultar Orden de Compra',
    'BUSCAR_ITEM'                               => 'Buscar Orden de Compra',
    'CONFIRMAR_ACCION_FACTURA'                  => 'Qué desea hacer con la Orden de compra N° %1',
    'ACCION_EJECUTADA'                          => 'Acción Ejecutada',
    'GENERAR_ORDEN_COMPRA'                      => 'Generar Orden de Compra',
    'IMPRIMIR_FACTURA_IMPRESORA'                => 'Imprimir Factura en Impresora',
    'IMPRIMIR_FACTURA_POS'                      => 'Imprimir factura POS',
    'ORDEN_GENERADA_EXITOSAMENTE'               => 'Orden generada exitosamente',
    'ORDEN_COMPRA_NUM'                          => 'Orden de compra número:  %1 ',
    'NUMERO_ORDEN'                              => 'Número de Orden',
    'USUARIO_CREADOR'                           => 'Usuario Creador',
    'FECHA_ORDEN'                               => 'Fecha de Orden',
    'USUARIO_QUE_GENERA_ORDEN'                  => 'Usuario Creador de la orden',
    'MODIFICAR_ITEM_DESDE_FORMULARIO'           => '.: Click aquí para facturar a partir de esta orden :.',
    'TIPO_DE_FACTURA'                           => 'ORDEN DE COMPRA',
    'FECHA_FACTURA'                             => 'Fecha de Factura',
    'USUARIO_QUE_FACTURA'                       => 'Usuario que Factura',
    'FECHA_VENCIMIENTO'                         => 'Fecha de Vencimiento',
    'DESCUENTOS'                                => 'Descuentos',
    'TOTAL_DESCUENTOS'                          => 'Total descuentos',
    'PAGINA'                                    => 'Página',
    'EMAIL'                                     => 'E-mail',
    'NOTA'                                      => 'Nota',    
    
    /*Campos y labels*/
    'NOMBRE'                                    => 'Nombre',
    'CODIGO'                                    => 'Codigo',
    'NUMERO_FACTURA'                            => 'Factura de Compra N°:',
    'NUMERO_FACTURA_PROVEEDOR'                  => 'Numero Factura del Proveedor: ',
    'FECHA'                                     => 'Fecha (A-m-d): ',
    'PROVEEDOR'                                 => 'Proveedor ',
    'OBSERVACIONES'                             => 'Observaciones: ',
    'LISTA_ARTICULOS'                           => 'Listado de Articulos: ',
    'CONCEPTO'                                  => 'Concepto: ',
    'DESCUENTO1'                                => 'Descuento 1: ',
    'DESCUENTO2'                                => 'Descuento 2: ',
    'MAS_DESCUENTO'                             => '+ dcto',
    'ARTICULO'                                  => 'Articulo: ',
    'VALOR_FLETE'                               => 'Valor flete: ',
    'IVA'                                       => 'I.V.A: ',
    'MODO_PAGO'                                 => 'Modo de Pago',
    'CREDITO'                                   => 'Credito',
    'CONTADO'                                   => 'Contado',
    'VENCIMIENTO'                               => 'Vencimiento (A-m-d): ',
    'TOTAL'                                     => 'Total: ',
    'AGREGAR'                                   => 'Agregar',
    'DESCUENTO_GENERAL'                         => 'Descuento General: ',
    'DESCUENTO'                                 => 'Descuento',
    'SUBTOTAL'                                  => 'Subtotal',
    'REFERENCIA'                                => 'Referencia',
    'FINALIZAR_FACTURA'                         => 'Finalizar Factura',
    'PRECIO_UNITARIO'                           => 'Precio U.',
    'VER_MAS'                                   => 'Click para ver más sobre el item',
    'MOTO'                                      => 'Moto',
    'SUBGRUPO'                                  => 'Subgrupo',
    'GRUPO'                                     => 'Grupo',
    'PRESENTACION'                              => 'Presentacion (empaque)',
    'PLU'                                       => 'Plu',
    'LINEA'                                     => 'Linea',
    'MARCA'                                     => 'Marca',
    'MODELO'                                    => 'Modelo',
    'MEDIDAS'                                   => 'Medidas',
    'CANTIDAD'                                  => 'Cantidad',
    'PRECIO_COMPRA'                             => 'Precio de Compra',
    'PRECIO_COMPRA_ANTERIOR'                    => 'Precio de Compra Anterior',
    'MARGEN_GANANCIA'                           => 'Margen de Ganancia',
    'APLICACION_EXTRA'                          => 'Aplicacion extra',
    'NACIONALIDAD'                              => 'Nacionalidad',
    'MARGEN_GANANCIA_PESOS'                     => 'Margen de Ganancia en Pesos',
    'MARGEN_GANANCIA_PORCENTAJE'                => 'Margen de Ganancia en Procentaje',
    'PRECIO_BASE'                               => 'Precio Venta',
    'LARGO'                                     => 'Largo',
    'ANCHO'                                     => 'Ancho',
    'ALTO'                                      => 'Alto',
    'EL_CODIGO'                                 => 'Codigo: %1',
    'EL_NOMBRE'                                 => 'Nombre: %1',
    'CODIGO_COMERCIAL'                          => 'Codigo comercial',
    'CODIGO_ISO'                                => 'Codigo iso',
    'AYUDA_CODIGO_ISO'                          => 'Codigo iso internacional del pais<br> compuesto por dos letras mayusculas',
    'BANDERA'                                   => 'Bandera',
    'SELECCIONAR_MOTOS_APLICACION'              => 'Seleccione a que motos sirve este articulo',
    'APLICA_SOLO_SU_MOTO'                       => 'Sirve solo a una moto',
    'APLICA_VARIAS_MOTOS'                       => 'Sirve a varias motos',
    'LLEVA_IVA'                                 => 'Lleva iva',
    'NO_LLEVA_IVA'                              => 'No lleva iva',
    'MOTOS_APLICABLE'                           => 'Aplica a las siguientes motos',
    'TEXTO_IVA_1'                               => 'Aplica IVA',
    'TEXTO_IVA_2'                               => 'NO Aplica IVA',
    'APLICABILIDAD_MOTOS'                       => 'Otras motos en que aplica',
    'PRECIOS'                                   => 'Precios',
    'PRECIO'                                    => 'Precio',
    'UBICACION'                                 => 'Ubicación',
    'BODEGA'                                    => 'Bodega',
    'GONDOLA'                                   => 'Gondola',
    'SEDE'                                      => 'Sede',
    'CONCEPTO1'                                 => 'Concepto1',
    'PRECIOS'                                   => 'Precios',
    'PRECIO1'                                   => 'Precio1',
    'CONCEPTO2'                                 => 'Concepto2',
    'PRECIO2'                                   => 'Precio2',
    'CONCEPTO3'                                 => 'Concepto3',
    'PRECIO3'                                   => 'Precio3',
    'CONCEPTO4'                                 => 'Concepto 4',
    'PRECIO4'                                   => 'Precio4',  
    'PRECIO_VENTA1'                             => 'Precio de venta 1',
    'PRECIO_VENTA2'                             => 'Precio de venta 2',
    'PRECIO_VENTA3'                             => 'Precio de venta 3',
    'PRECIO_VENTA4'                             => 'Precio de venta 4',
    'INFORMACION_ARTICULO'                      => 'Información Articulo',
    'INFORMACION_APLICABILIDAD'                 => 'Información de aplicación',
    'INFORMACION_PRECIOS'                       => 'Información precios',
    'BUSCAR_FACTURAS'                           => 'Buscar Facturas',
    'FECHA_INICIAL'                             => 'Fecha inicial',
    'FECHA_FINAL'                               => 'Fecha final',
    'AGREGAR_VARIOS_ARTICULOS'                  => 'Agregar multiples articulos',
    'ID_AUTOMATICO'                             => 'Id auto.',
    
    /*Errores*/
    'ERROR_FALTA_CODIGO'                        => 'Error falta codigo',
    'ERROR_EXISTE_CODIGO'                       => 'Error existe un pais con este codigo iso',
    'ERROR_EXISTE_CODIGO_COMERCIAL'             => 'Error existe un pais con este codigo comercial',
    'ERROR_FALTA_NOMBRE'                        => 'Error falta nombre', 
    'ERROR_EXISTE_NOMBRE'                       => 'Error existe un articulo registrado con ese nombre',
    'ERROR_FORMATO_CODIGO'                      => 'Error formato codigo iso, solo deben ser dos letras mayusculas',
    'ERROR_FORMATO_NOMBRE'                      => 'Error formto nombre, deben ser solo letras',
    'ERROR_FALTA_SUBGRUPO'                      => 'Error falta subgrupo',
    'ERROR_SUBGRUPO_INEXISTENTE'                => 'Error, debe seleccionar un subgrupo de la lista',
    'ERROR_FALTA_GRUPO'                         => 'Error falta grupo',
    'ERROR_GRUPO_INEXISTENTE'                   => 'Error, debe seleccionar un grupo de la lista',    
    'ERROR_MOTO_INEXISTENTE'                    => 'Error, debe seleccionar una moto de la lista',
    'ERROR_PAIS_INEXISTENTE'                    => 'Error, debe seleccionar un pais de la lista',
    'ERROR_UNIDAD_INEXISTENTE'                  => 'Error, debe seleccionar una unidad de la lista',
    'ERROR_MARCA_INEXISTENTE'                   => 'Error, debe seleccionar una marca de la lista',
    'ERROR_FALTA_REFERENCIA'                    => 'Error, falta referencia',
    'ERROR_FALTA_UNIDAD'                        => 'Error, falta unidad',
    'ERROR_FALTA_PAIS'                          => 'Error, falta pais',
    'ERROR_FALTA_PRECIO_BASE'                   => 'Error, debes introducir almenos un precio de venta',
    'ERROR_FALTA_PRECIO_COMPRA'                 => 'Error, falta precio compra',
    'ERROR_FALTA_MARGEN_GANANCIA'               => 'Error, falta margen ganancia',
    
    /*Ayuda*/
    'AYUDA_CODIGO_COMERCIAL'                    => 'Codigo comercial del pais<br>Ejemplo: Taiwan TAW',
    'AYUDA_MODULO'                              => '<p>* F1 Para agregar varios articulos al tiempo </p><p>* F2 Para buscar facturas  </p><p>* Shift + M para cerrar el menu superior.</p><p><p class = \'videotutorialAyuda\'>* <a onclick=\'cerrarAyuda()\' rel=\'prettyPhoto[]\' href=\'http://www.youtube.com/watch?v=x6UODla2hqE\' target=\'blank\'>Click Aqui para ver video de ayuda paso a paso</a></p>*Para cerrar esta ventana presione Ctrl+H, o haga click en cualquier lugar <br>'
);

?>