<?php
/**
 * @package     FOM
 * @subpackage  Textos Ventas
 * @author      Pablo Andrés Vélez Vidal. <pavelez@genesyscorp.com.co>
 * @license     http://www.gnu.org/licenses/gpl.txt
 * @copyright   Copyright (c) 2013 Genesys corporation
 * @version     0.1
 **/
$textos = array(
    /*Basicos*/
    'MODULO_ACTUAL'                             => 'Ventas',
    'ADICIONAR_ITEM'                            => 'Agregar Venta',
    'MODIFICAR_ITEM'                            => 'Modificar Venta',
    'ELIMINAR_ITEM'                             => 'Eliminar Venta',
    'CONSULTAR_ITEM'                            => 'Consultar Venta',
    'BUSCAR_ITEM'                               => 'Buscar Venta',
    'CONFIRMAR_ACCION_FACTURA'                  => 'Qué desea hacer con la factura de venta?',
    'ACCION_EJECUTADA'                          => 'Acción Ejecutada',
    'GENERAR_COTIZACION'                        => 'Generar Cotización ......................... Ctrl + O',
    'IMPRIMIR_FACTURA_IMPRESORA'                => 'Imprimir Factura en Impresora ........ Ctrl + I',
    'IMPRIMIR_FACTURA_POS'                      => 'Imprimir factura POS ........................ Ctrl + P',
    'CANCELAR'                                  => 'Cancelar ............................................ Ctrl + Q',
    'FACTURA_VENTA_NUM'                         => 'Factura de venta número:  %1 ',
    'GENERAR_FACTURA_DESDE_FACTURA_TEMPORAL'    => 'Recuperar factura fecha %1',
    'MODIFICAR_FACTURA'                         => 'Modificar Factura',
    'GENERAR_FACTURA_DESDE_COTIZACION'          => 'Generar Factura desde Cotización N° %1',
    'CREAR_COTIZACION'                          => 'Crear cotización',
    'SELECCIONAR'                               => 'Seleccionar',
    'SELECCIONE_FECHA_FINAL'                    => 'Seleccione fecha final',
    'SELECCIONE_FECHA_INICIAL'                  => 'Seleccione fecha inicial',
    'NUMERO_DE_FACTURA'                         => 'Numero de factura',
    'AYUDA_SELECCIONAR_ITEMS_TABLA_FACTURAS'    => '*Haga click derecho sobre una fila para ver la factura en detalle',
    'BUSCAR_COTIZACIONES'                       => 'Buscar Cotizaciones',
    'TOTAL_IVA'                                 => 'Total IVA',
    'IVA_FLETE'                                 => 'Iva flete',
    'CREDITO'                                   => 'Crédito',
    'CANCELA_CON'                               => 'Cancela con: ',
    'DEBE_DEVOLVER'                             => '..... y debe devolver: ',
    'VENDEDOR'                                  => 'Vendedor',
    'ACTUALIZAR_RETENCIONES'                    => 'Actualizar retenciones',
    'TOTAL_RETENCIONES'                         => 'Total retenciones',
    'TOTAL_A_PAGAR'                             => 'Total a pagar',
    
    'MENSAJE_FACTURA_TEMPORAL_VENTA'            => 'Tienes una factura de <span class=negrilla>venta</span> sin finalizar realizada el <span class=negrilla>%1</span> al cliente <span class=negrilla>%2</span>', 
    
    'NIT'                                       => 'Nit: ',
    'SOLO_PUEDE_SER_COTIZACION'                 => '* Falta el campo \'Número de factura de cliente\', solo puedes ejecutar una cotización.',
    'CREAR_FACTURA_CLIENTE'                     => 'Generar factura de cliente',
    'EDITAR_FACTURA_CLIENTE'                    => 'Editar factura de cliente',
    'HORA'                                      => 'Hora',
    'CATALOGOS'                                 => 'Catálogos',
    'BUSCAR_CATALOGOS'                          => 'Click aquí para buscar el<br> catálogo de una moto',
    'TIPO_DE_FACTURA'                           => 'FACTURA DE VENTA',
    'FECHA_FACTURA'                             => 'Fecha de Factura',
    'USUARIO_QUE_FACTURA'                       => 'Usuario que Factura',
    'FECHA_VENCIMIENTO'                         => 'Fecha de Vencimiento',
    'FECHA_COTIZACION'                          => 'Fecha cotización',
    'DESCUENTOS'                                => 'Descuentos',
    'TOTAL_DESCUENTOS'                          => 'Total descuentos',
    'NUMERO_COTIZACION'                         => 'N° cotización',
    'INGRESE_NUM_COTIZACION'                    => 'Ingrese número de cotización',
    'BUSQUEDA_AVANZADA'                         => 'Busqueda avanzada >>',
    'BUSCAR_COTIZACION'                         => 'Buscar Cotización',
    'PAGINA'                                    => 'Página',
    'EMAIL'                                     => 'E-mail',
    'NOTA'                                      => 'Nota',
    'MOVER'                                     => 'Mover',
    'MOVER_ARTICULO_BODEGA'                     => 'Mover articulo a bodega diferente',
    'LISTAR_TODOS_ARTICULOS'                    => 'Listar todos los articulos',
    'CLIENTE_ESTANDAR'                          => 'VENTA VARIOS DE CONTADO',
    'GENERAR_ORDEN_VENTA'                       => 'Generar cotización',
    'FECHA_LIMITE_PAGO_PARA_DESCUENTO'          => 'Pague antes del ',
    'PORCENTAJE_DESCUENTO'                      => 'Y reciba un descuento del',
    'TEXTO_DCTO_EXTRA'                          => '+ Dcto. pronto pago.',
    'CARGAR_COTIZACION'                         => 'Cargar Cotización',
    'DESCUENTO_TITULO'                          => '<span ayuda="Descuento unitario <br> articulo" > Dcto.</span>',
    'AYUDA_TEXTO_DCTO_EXTRA'                    => 'Click aquí para mostrar/ocultar el<br>formulario para agregar hasta<br>2 descuento por pagos tempranos.',
    'AYUDA_PORCENTAJE_DCTO_1'                   => 'Ingresa el descuento en porcentaje.',
    'AYUDA_FECHA_DCTO'                          => 'Selecciona la fecha antes de la cual<br>se debe pagar esta factura para que <br>aplique el descuento',
    'VALIDAR_DESCUENTO'                         => 'Validar descuento',
    'MAXIMO_DESCUENTO_PERMITIDO'                => 'Ingrese el descuento para<br> todos los articulos. <br>Maximo descuento permitido %1 %',
    'EXPLICACION_AUTORIZACION_DCTO'             => '* El descuento que intenta aplicar (<span id="txtValDcto" class="negrilla"></span>) supera su autorizado. Solicite a su supervisor el ingreso de usuario y contraseña para validar la autorizacion del descuento',
    

    
    /*Campos y labels*/
    'NOMBRE'                                    => 'Nombre',
    'CODIGO'                                    => 'Codigo',
    'NUMERO_FACTURA'                            => 'Factura de Venta N°',
    'NUMERO_FACTURA_CLIENTE'                    => 'Numero Factura del Cliente',
    'FECHA'                                     => 'Fecha (A-m-d): ',
    'CLIENTE'                                   => 'Cliente',
    'OBSERVACIONES'                             => 'Observaciones',
    'LISTA_ARTICULOS'                           => 'Listado de Articulos',
    'CONCEPTO'                                  => 'Concepto: ',
    'DESCUENTO1'                                => 'Descuento 1',
    'DESCUENTO2'                                => 'Descuento 2',
    'MAS_DESCUENTO'                             => '+ Dcto',
    'ARTICULO'                                  => 'Articulo',
    'VALOR_FLETE'                               => 'Valor flete',
    'IVA'                                       => 'IVA',
    'MODO_PAGO'                                 => 'Modo de Pago',
    'MODO_PAGO2'                                => 'Credito',
    'MODO_PAGO1'                                => 'Contado',
    'PAGANDO_EN_TOTAL'                          => 'Pagando en total',    
    'INFORMACION_RESOLUCION_FACTURA'            => 'Resolución de la DIAN N° %1 de Fecha %2 Facturacion autorizada de %3 hasta %4',
    'VENCIMIENTO'                               => 'Vencimiento',
    'TOTAL'                                     => 'Total: ',
    'AGREGAR'                                   => 'Agregar',
    'DESCUENTO_GENERAL'                         => 'Descuento General: ',
    'DESCUENTO'                                 => 'Descuento',
    'SUBTOTAL'                                  => 'Subtotal',
    'REFERENCIA'                                => 'Referencia',
    'FINALIZAR_FACTURA'                         => 'Fin Factura',
    'PRECIO_UNITARIO'                           => 'Precio U.',
    'VER_MAS'                                   => 'Click para ver más sobre el item',
    'MOTO'                                      => 'Moto',
    'SUBGRUPO'                                  => 'Subgrupo',
    'GRUPO'                                     => 'Grupo',
    'PRESENTACION'                              => 'Presentacion (empaque)',
    'PLU'                                       => 'Plu',
    'LINEA'                                     => 'Linea',
    'MARCA'                                     => 'Marca',
    'MODELO'                                    => 'Modelo',
    'MEDIDAS'                                   => 'Medidas',
    'CANTIDAD'                                  => 'Cantidad',
    'PRECIO_VENTA'                              => 'Precio de Venta',
    'PRECIO_VENTA_ANTERIOR'                     => 'Precio de Venta Anterior',
    'MARGEN_GANANCIA'                           => 'Margen de Ganancia',
    'APLICACION_EXTRA'                          => 'Aplicacion extra',
    'NACIONALIDAD'                              => 'Nacionalidad',
    'MARGEN_GANANCIA_PESOS'                     => 'Margen de Ganancia en Pesos',
    'MARGEN_GANANCIA_PORCENTAJE'                => 'Margen de Ganancia en Porcentaje',
    'PRECIO_BASE'                               => 'Precio Venta',
    'LARGO'                                     => 'Largo',
    'ANCHO'                                     => 'Ancho',
    'ALTO'                                      => 'Alto',
    'EL_CODIGO'                                 => 'Codigo: %1',
    'EL_NOMBRE'                                 => 'Nombre: %1',
    'CODIGO_COMERCIAL'                          => 'Codigo comercial',
    'CODIGO_ISO'                                => 'Codigo iso',
    'AYUDA_CODIGO_ISO'                          => 'Codigo iso internacional del pais<br> compuesto por dos letras mayusculas',
    'BANDERA'                                   => 'Bandera',
    'SELECCIONAR_MOTOS_APLICACION'              => 'Seleccione a que motos sirve este articulo',
    'APLICA_SOLO_SU_MOTO'                       => 'Sirve solo a una moto',
    'APLICA_VARIAS_MOTOS'                       => 'Sirve a varias motos',
    'LLEVA_IVA'                                 => 'Lleva iva',
    'NO_LLEVA_IVA'                              => 'No lleva iva',
    'MOTOS_APLICABLE'                           => 'Aplica a las siguientes motos',
    'TEXTO_IVA_1'                               => 'Aplica IVA',
    'TEXTO_IVA_2'                               => 'NO Aplica IVA',
    'APLICABILIDAD_MOTOS'                       => 'Otras motos en que aplica',
    'PRECIOS'                                   => 'Precios',
    'PRECIO'                                    => 'Precio',
    'UBICACION'                                 => 'Ubicación',
    'BODEGA'                                    => 'Bodega',
    'GONDOLA'                                   => 'Gondola',
    'SEDE'                                      => 'Sede',
    'CONCEPTO1'                                 => 'Concepto1',
    'PRECIOS'                                   => 'Precios',
    'PRECIO1'                                   => 'Precio1',
    'CONCEPTO2'                                 => 'Concepto2',
    'PRECIO2'                                   => 'Precio2',
    'CONCEPTO3'                                 => 'Concepto3',
    'PRECIO3'                                   => 'Precio3',
    'CONCEPTO4'                                 => 'Concepto 4',
    'PRECIO4'                                   => 'Precio4',  
    'PRECIO_VENTA1'                             => 'Precio de venta 1',
    'PRECIO_VENTA2'                             => 'Precio de venta 2',
    'PRECIO_VENTA3'                             => 'Precio de venta 3',
    'PRECIO_VENTA4'                             => 'Precio de venta 4',
    'INFORMACION_ARTICULO'                      => 'Información Articulo',
    'INFORMACION_APLICABILIDAD'                 => 'Información de aplicación',
    'INFORMACION_PRECIOS'                       => 'Información precios',
    'AYUDA_BUSCAR_FACTURAS'                     => 'Click aquí para Buscar<br> Facturas en el sistema',
    'BUSCAR_FACTURAS'                           => 'Buscar Factura',
    'FECHA_INICIAL'                             => 'Fecha inicial',
    'CAJA'                                      => 'Caja',
    'FECHA_FINAL'                               => 'Fecha final',
    'NUMERO'                                    => 'Numero',
    'ID_CLIENTE'                                => 'Nit cliente',
    'AGREGAR_VARIOS_ARTICULOS'                  => 'Agregar multiples articulos',
    'FACTURA_GENERADA_EXITOSAMENTE'             => 'Factura generada exitosamente',
    'NOTA_RESOLUCION_DIAN_EN_FACTURA'           => 'Resolución de la DIAN N° %1 con fecha %2 rango de facturación autorizado desde %3 hasta %4',
    'ID_AUTOMATICO'                             => 'Id Auto.',
    'PORCENTAJE_IVA'                            => '% IVA',
    'IVA_TOTAL'                                 => 'IVA total',
    
    
    /*Errores*/
    'ERROR_FALTA_CODIGO'                        => 'Error falta codigo',
    'ERROR_EXISTE_CODIGO'                       => 'Error existe un pais con este codigo iso',
    'ERROR_EXISTE_CODIGO_COMERCIAL'             => 'Error existe un pais con este codigo comercial',
    'ERROR_FALTA_NOMBRE'                        => 'Error falta nombre', 
    'ERROR_EXISTE_NOMBRE'                       => 'Error existe un articulo registrado con ese nombre',
    'ERROR_FORMATO_CODIGO'                      => 'Error formato codigo iso, solo deben ser dos letras mayusculas',
    'ERROR_FORMATO_NOMBRE'                      => 'Error formto nombre, deben ser solo letras',
    'ERROR_FALTA_SUBGRUPO'                      => 'Error falta subgrupo',
    'ERROR_SUBGRUPO_INEXISTENTE'                => 'Error, debe seleccionar un subgrupo de la lista',
    'ERROR_FALTA_GRUPO'                         => 'Error falta grupo',
    'ERROR_GRUPO_INEXISTENTE'                   => 'Error, debe seleccionar un grupo de la lista',    
    'ERROR_MOTO_INEXISTENTE'                    => 'Error, debe seleccionar una moto de la lista',
    'ERROR_PAIS_INEXISTENTE'                    => 'Error, debe seleccionar un pais de la lista',
    'ERROR_UNIDAD_INEXISTENTE'                  => 'Error, debe seleccionar una unidad de la lista',
    'ERROR_MARCA_INEXISTENTE'                   => 'Error, debe seleccionar una marca de la lista',
    'ERROR_FALTA_REFERENCIA'                    => 'Error, falta referencia',
    'ERROR_FALTA_UNIDAD'                        => 'Error, falta unidad',
    'ERROR_FALTA_PAIS'                          => 'Error, falta pais',
    'ERROR_FALTA_PRECIO_BASE'                   => 'Error, debes introducir almenos un precio de venta',
    'ERROR_FALTA_PRECIO_VENTA'                  => 'Error, falta precio venta',
    'ERROR_FALTA_MARGEN_GANANCIA'               => 'Error, falta margen ganancia',
    'ERROR_SEDE_SIN_RESOLUCION'                 => 'La sede %1 no tiene una resolución de la DIAN asignada, sin ello no puedes facturar',
    'ERROR_NUMERO_FUERA_RESOLUCION'             => 'Error, el número de factura %1 que esta intentando crear esta fuera del rango de la resolución de la DIAN actual que es la %2 con fecha %3 que permite la facturacion entre los números %4',
    
    /*Ayuda*/
    'AYUDA_SELECCIONAR_VENDEDOR'                => 'Seleccione el vendedor que va a realizar la venta',
    'AYUDA_FECHA_FACTURA'                       => 'Aquí puedes cambiar la<br> fecha de la factura',
    'SELECCIONE_MEDIO_DE_PAGO'                  => 'Selecciona la forma de pago',
    'AYUDA_FECHA_VTO_FACTURA'                   => 'Selecciona la fecha límite<br> para el pago de la factura',    
    'AYUDA_CARGAR_COTIZACION'                   => 'Click aquí para buscar una Cotización<br>y cargarla.',
    'AYUDA_MODULO'                              => '<p>* F1 Para agregar varios articulos al tiempo </p><p>* F2 Para buscar facturas  </p><p>* Shift + M para cerrar el menu superior.</p><p><p class = \'videotutorialAyuda\'>* <a onclick=\'cerrarAyuda()\' rel=\'prettyPhoto[]\' href=\'http://www.youtube.com/watch?v=x6UODla2hqE\' target=\'blank\'>Click Aqui para ver video de ayuda paso a paso</a></p>*Para cerrar esta ventana presione Ctrl+H, o haga click en cualquier lugar <br>',
    
    /* Ayuda tutorial*/
    'AYUDA_SELECCIONAR_CLIENTE'                 => 'Seleccione el cliente al que se le va a realizar la venta',
    'AYUDA_INGRESAR_ARTICULO_A_LA_FACTURA'      => 'escribe algún caracter para iniciar la busqueda de un articulo, puedes buscar por descripción, PLU, o referencia. Al seleccionarlo ya sea haciendo click con el mouse, o moviendose con las flechas del teclado y presionando enter, automáticamente se agregará al listado de articulos',
    'AYUDA_INGRESA_NUM_FACTURA_CLIENTE'         => 'Ingrese aquí el número de factura del cliente. Si no se ingresa valores en este campo, solo se podrá realizar una cotización.',
    'AYUDA_INGRESA_FECHA_VENTA'                 => 'Ingrese aquí la fecha en la que se ejecuta esta venta, por defecto es la fecha actual.',
    'AYUDA_BUSCAR_FACTURAS_ANTERIORES'          => 'Click aquí para desplegar el formulario donde podras buscar facturas de venta realizadas en el sistema. En dicho formulario podras escoger un cliente en particular y un rango de fechas, al hacer click en aceptar el sistema mostrará un listado con las facturas realizadas al cliente seleccionado en el rango de fechas seleccionado.',
    'AYUDA_BUSCAR_CATALOGO_MOTO'                => 'Click aquí para desplegar el formulario donde podras buscar el catálogo de una moto. El formulario mostrará un campo de texto autocompletable donde podras buscar y seleccionar una moto en particular y el sistema desplegará el catálogo de dicha moto.',
    'AYUDA_BUSCAR_Y_CARGAR_ORDEN_DE_VENTA'      => 'Click aquí para desplegar el formulario donde podras buscar cotizaciones realizadas en el sistema. Podras realizar una busqueda simple (por el número de cotización), o más avanzada (escoger un cliente y un rango de fechas), el sistema desplegará un listado con todas las cotizaciones coincidientes. Haga click derecho sobre la cotización que desea consultar y allí encontrará la opción para generar una factura a partir de dicha cotización.',
    'AYUDA_CARGAR_MULTIPLES_ARTICULOS'          => 'Click aquí para que el sistema muestre el listado general de articulos. Allí podras buscar los articulos que necesites e inclusive parametrizar dichas busquedas (buscar por descripcion, linea, subgrupo, etc.). Una vez tengas en pantalla los articulos que necesitas podras seleccionar varios articulos y agregarlos simultaneamente.',
    'AYUDA_DESCUENTO_GENERAL'                   => 'Ingresa aquí un valor (porcentaje de descuento) y este se aplicará a todos los articulos del listado de articulos a ventar. Este será el descuento a aplicar a este articulo.',
    'AYUDA_GANANCIA_GENERAL'                    => 'Ingresa aquí un valor (porcentaje de ganancia) y este se aplicará a todos los articulos del listado de articulos a ventar. Este valor será el porcentaje de ganancia del articulo respecto a su precio de venta.',
    'AYUDA_BORRAR_LISTADO_ARTICULOS'            => 'Click aquí para borrar todos los articulos de listado de ventas.',
    'AYUDA_VALOR_FLETE'                         => 'Ingresa aquí el valor del flete.',
    'AYUDA_CONCEPTO_DESCUENTO'                  => 'Ingresa aquí el concepto del descuento (Solo ingresar valores si se va a realizar un descuento).',
    'AYUDA_DESCUENTO'                           => 'Ingresa aquí el valor en porcentaje del descuento (Solo ingresar valores si se va a realizar un descuento)',
    'AYUDA_MAS_DESCUENTO'                       => 'Haga click aquí si necesita aplicar más descuentos sobre esta factura.',
    'AYUDA_GUIA_SUBTOTAL'                       => 'Aquí aparece el subtotal de la factura.',
    'AYUDA_OBSERVACIONES'                       => 'Ingrese aquí las observaciones correspondientes a esta factura.',
    'AYUDA_IVA'                                 => 'Aquí se verá reflejado el iva total de la factura',
    'AYUDA_DCTO_PRONTO_PAGO'                    => 'Click aquí para desplegar el formulario donde agregaras las notas de descuento por pronto pago',
    'AYUDA_LISTADO_ARTICULOS'                   => 'Aquí aparecen los articulos que se van ingresando para la venta. Dispones de diversas opciones en dicho listado, por favor presta mucha atención a todas las ayudas ofrecidas por el sistema.',
    'AYUDA_TOTAL'                               => 'Aquí aparece el total de la factura.',
    'AYUDA_FINALIZAR_FACTURA'                   => 'Click aquí para desplegar el formulario de finalización de la factura.'      
    
    
);
